server:
  port: 8082

spring:
  application:
    name: service-verificationcode
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:9091  #设置sentinel控制台的ip和端口地址
