spring:
  cloud:
    #配置nacos
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: service-order

  #配置数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 106331
    url: jdbc:mysql://localhost:3306/service-order?characterEncoding=utf-8&serverTimezone=GMT%2B8
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: 106331



logging:
  level:
    root: info
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  global-config:
    db-config:
      id-type: AUTO
---
spring:
  profiles: 8007
server:
  port: 8007
---
spring:
  profiles: 8008
server:
  port: 8008



zookeeper:
  address: localhost:2181
  timeout: 100000

seata:
  service:
    vgroup-mapping:
      my_tx: seata-tc
    grouplist:
      #    grouplist.seata-tc: 127.0.0.1:8091;127.0.0.1:8092;127.0.0.1:8093
      seata-tc: 127.0.0.1:8091
  tx-service-group: my_tx