server:
  port: 9001

spring:
  application:
    name: service-alipay
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848




#自定义配置
alipay:
  appid: 9021000135671467
  appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCFr/bnjZrmv8ypvRhqbWqHYSrdlF0jY+TFeh/ls08pTns5Mh6Kn3TtKdQVApniMQPC9F+hg3tU2kM30P2yegeRuesLmkhQG6GoJ/V9ReGPOVsgi1Etpaxg+SPpwbB2eQ0Pz5/3deapFsXzW9JlVEaovkKHthxywyHB7Qlzjxv23gphaQ0tau0jG8RkbwnKq2EFcWEJ9JMgGk0yVwfCFQz39OYAtOpp7YX3wUTIDofTiXmcnWg9us+DHrJ1yNSYLvhG/+mK4ubrNmC0NGlOUDsmYQ5Vs18Y/YoUm0v3KLwLagXUuryXYQdSlFUaZ00/fNn5MB7D72PxgWQpu2MJgRNtAgMBAAECggEAMGd6/XH/IQdXIiouWfKN/MCI1buvUW4M2heSzwdyZSFeamIkPsrneiuH96d+cjCPDRqQOZmyoRF5/w6znNikPvZTDVtqTV8D1C/LqfUQa1w4C3uGBAIVfPMYNr4Dl5HS0eO6Js5Qmu5889VOQ5QVFWn2Cs88U60lXuLlZirt1B8dI4RF5hlDptKM4ideGJE8RTHIDEdkvgp2hnSHmKvnM7ieuddkyKJ9IEJOBxUxzQHc1jYfE44mvz8abahNGqbT4pIw6P0jFtdmkEn8Nnd9dvjcTZlWSchrg6ZN2CE2Pwy/34hOBtBGFrjS4G9U4FZ25b8ZzHUunxUSQIOrE6LsIQKBgQDsPUzcNQRelySblsDiT6A439gob6OWX8V5G+oiJupb618MujN3LmMUvMVF9RBwDNvrFhA22bqv+fngMbAVhULXgFHj0viHfkdQBw13+Odf3JRhqmGdjUsqTjVE1F0Cpxqq0yDco4aKhJnLo3udO4ZjEUCgY8NnecZNCwm+nhi9CQKBgQCQ3qvFUZvdjMW9ka7MgIVDPi9XHKs7luxFaSahhI87GknkmS0yMwPTfqJiFbpMnayvPwu/43FCP6/H00jNBiDCX15P0pWKw1rpzErlM9bKwV1jZk8txkVHGdl1mDTPjzG7K/nwtK8CzvYbc5h2OaG9bZVUEWfA6ZMB6glCjc0gRQKBgD2objQXPlG13x8gxK0MnUPa4J8FLEwmKPNIHt7VC1v8Xa2Dt8UGfWO/NTniEW09XfTIqGi4gSpG8znZnhyv0FdQrY7p1GYAxnoTrSc/9pulhbDL+HhXlWOwT+TsDG6R0Lr/KdeMcqQaoc1tmOjbzWJz8UsrXqfWN7SKCfwPZWOJAoGAEoUEvHLUVBw84yEOkYIUhyYZ8y7tDO8cQTtR/u/tR4byz1BtoK842/6iT5urd0Po4XZT0DIJNojhtc/izKLt6Ss76URobZbPtnexU1+vI7hYce6QTK++B3rce9X7WlVZ7C2RBB51CQzgFV5PrT1s2cR6hIa9FsJFUsdSa7mo8WkCgYEAh51f0VyrRD2eZlswqERHqkvSpDn536jUHMyYOEN3Uei+1dMIzXA5smXYopf730dKOC4xcwhx8eZ0rfgXd4HUXqkDM5U6EAt/GLSydd07yJO6c1z30arwwW/Zzex/kJwhY43vEI8iAu+5KYJsjd/2vIu97lTT1+Sz8wngTlR34bE=
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuKeE2bGzvVvII5/LJ/EtLT98mGHcwG7h0G8OxfyDve96TRLh5wrTVzay1pGSkLYTZhOkoeYbUA8J7rXMHfPuKJjiBPZENBLW13Qvl54o4jiYp66g7Km/6NFVKMS5O2pK3yBF7la6PT8QJ8RXgag8KY09btsccpo7nBZREO+zTGS8DfsRNqG4uWIvcEgXiKsYQ2qMMstMuld88gPe0wCLPK+hTgN3gJzr6yWX+U7rBgMjAXs9QZi22G2nYYQcICjdS9B5N7LBhngviliRfUPNUZI3aE7B/bStiYjR9EwaclDKVQdqWceiCTIzV0UijMGd1w1Dke/7NgU0fnnKDrA+WwIDAQAB
#  支付宝要回调的我们的服务器的地址
#  https://4h97229n74.vicp.fun  映射到 127.0.0.1:9001
  notifyUrl: https://4h97229n74.vicp.fun/alipay/notify



